# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCNetworkiOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SCNetworkiOSDemo

  platform :ios, '7.0'

  pod 'SCNetworkKit', :path => '../../'
  pod 'SCJSONUtil'

end

target 'SCNetworkMacDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SCNetworkiOSDemo

  platform :osx, '10.11'

  pod 'SCNetworkKit', :path => '../../'
  pod 'SCJSONUtil'

end
